# Generated by Django 3.0.6 on 2020-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotonovs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Внести свободную дату с информацией')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
