# Generated by Django 3.0.6 on 2020-06-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotonovs', '0008_auto_20200529_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.AlterIndexTogether(
            name='photon',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='photon',
            name='album_n',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Albumn',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Photon',
        ),
    ]
