# Generated by Django 3.0.6 on 2020-06-01 16:13

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
                ('alt', models.CharField(default=uuid.uuid4, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Созданный')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=70, verbose_name='Уникальное поле слага')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foto.Album')),
            ],
        ),
    ]
